# This configuration uses ROP chains only.
# No opaque predicates and constants.
[general]
search_segment_for_gadget = true
avoid_multiversion_symbol = true
rng_seed = 19931210

[functions.default]
obfuscation_enabled = true
# opaque gadgets
opaque_gadget_addresses_enabled = false
gadget_addresses_obfuscation_percentage = 0
# opaque predicates
opaque_predicates_enabled = false
contextual_opaque_predicates_enabled = false
# opaque values
opaque_saved_stack_values_enabled = false
opaque_immediate_operands_enabled = false
opaque_branch_targets_enabled = false
